create table if not exists public.pos_users (
  id bigint primary key,
  full_name text not null,
  username text not null unique,
  password text not null,
  role text not null check (role in ('owner', 'employee'))
);

create table if not exists public.products (
  id bigint primary key,
  name text not null,
  price numeric(10,2) not null default 0,
  gender text not null check (gender in ('male', 'female'))
);

create table if not exists public.receipts (
  id text primary key,
  date date not null,
  time text not null,
  total numeric(10,2) not null default 0,
  items jsonb not null default '[]'::jsonb,
  payment text not null,
  pos text not null,
  refunded boolean not null default false,
  refund_of text null
);

create table if not exists public.inventory (
  id text primary key,
  name text not null,
  category text not null,
  qty integer not null default 0,
  min_stock integer not null default 1
);

create table if not exists public.inventory_history (
  id bigint generated by default as identity primary key,
  type text not null,
  description text not null,
  time text not null,
  date date not null
);

alter table public.pos_users enable row level security;
alter table public.products enable row level security;
alter table public.receipts enable row level security;
alter table public.inventory enable row level security;
alter table public.inventory_history enable row level security;

drop policy if exists "demo full access pos_users" on public.pos_users;
drop policy if exists "demo full access products" on public.products;
drop policy if exists "demo full access receipts" on public.receipts;
drop policy if exists "demo full access inventory" on public.inventory;
drop policy if exists "demo full access inventory_history" on public.inventory_history;

create policy "demo full access pos_users"
on public.pos_users
for all
to anon, authenticated
using (true)
with check (true);

create policy "demo full access products"
on public.products
for all
to anon, authenticated
using (true)
with check (true);

create policy "demo full access receipts"
on public.receipts
for all
to anon, authenticated
using (true)
with check (true);

create policy "demo full access inventory"
on public.inventory
for all
to anon, authenticated
using (true)
with check (true);

create policy "demo full access inventory_history"
on public.inventory_history
for all
to anon, authenticated
using (true)
with check (true);

insert into public.pos_users (id, full_name, username, password, role)
values
  (1, 'Store Owner', 'admin', 'owner123', 'owner'),
  (2, 'Staff Member', 'staff', 'emp123', 'employee')
on conflict (id) do nothing;

insert into public.products (id, name, price, gender)
values
  (1, '212 VIP Black 85ML', 150, 'male'),
  (2, 'Acqua Di Gio 85ML', 150, 'male'),
  (3, 'Baccarat Rouge 540 85ML', 150, 'female'),
  (4, 'Bombshell 85ML', 150, 'female'),
  (5, 'Burberry Blush 85ML', 150, 'female'),
  (6, 'Bvlgari Amethyste 85ML', 150, 'female'),
  (7, 'Bvlgari Extreme 85ML', 150, 'male'),
  (8, 'CK One 85ML', 150, 'male'),
  (9, 'Cloud Ariana Grande 85ML', 150, 'female'),
  (10, 'Cool Water 85ML', 150, 'male'),
  (11, 'D&G Light Blue 85ML', 150, 'male'),
  (12, 'Eclat D''Aperge 85ML', 150, 'female'),
  (13, 'Ferrari Black 85ML', 150, 'male'),
  (14, 'French Riviera 85ML', 150, 'female'),
  (15, 'Good Girl 85ML', 150, 'female'),
  (16, 'Hugo Boss 85ML', 150, 'male'),
  (17, 'Incanto Shine 85ML', 150, 'female'),
  (18, 'Lacoste Black 85ML', 150, 'male'),
  (19, 'Lacoste Red 85ML', 150, 'male'),
  (20, 'Meow Katy Perry 85ML', 150, 'female'),
  (21, 'Montblanc 85ML', 150, 'male'),
  (22, 'Polo Blue 85ML', 150, 'male'),
  (23, 'Polo Sport 85ML', 150, 'male'),
  (24, 'Ralph Lauren 85ML', 150, 'female'),
  (25, 'Sauvage Dior 85ML', 150, 'male'),
  (26, 'Valaya 85ML', 150, 'female'),
  (27, 'Miss Dior 85ML', 150, 'female'),
  (28, 'Chanel No.5 85ML', 150, 'female'),
  (29, 'Bleu de Chanel 85ML', 150, 'male'),
  (30, 'Versace Eros 85ML', 150, 'male')
on conflict (id) do nothing;

insert into public.inventory (id, name, category, qty, min_stock)
values
  ('PRD-001', '212 VIP Black 85ML', 'Perfume', 24, 5),
  ('PRD-002', 'Acqua Di Gio 85ML', 'Cologne', 7, 5),
  ('PRD-003', 'Baccarat Rouge 540 85ML', 'Perfume', 5, 5),
  ('PRD-004', 'Bombshell 85ML', 'Perfume', 0, 4),
  ('PRD-005', 'Burberry Blush 85ML', 'Perfume', 15, 6),
  ('PRD-006', 'Bvlgari Amethyste 85ML', 'Cologne', 3, 5),
  ('PRD-007', 'Bvlgari Extreme 85ML', 'Cologne', 20, 5),
  ('PRD-008', 'CK One 85ML', 'Body Spray', 8, 6),
  ('PRD-009', 'Cloud Ariana Grande 85ML', 'Perfume', 4, 4),
  ('PRD-010', 'Cool Water 85ML', 'Cologne', 0, 5),
  ('PRD-011', 'D&G Light Blue 85ML', 'Cologne', 12, 5),
  ('PRD-012', 'Eclat D''Aperge 85ML', 'Perfume', 6, 5),
  ('PRD-013', 'Ferrari Black 85ML', 'Cologne', 30, 8),
  ('PRD-014', 'French Riviera 85ML', 'Perfume', 2, 4),
  ('PRD-015', 'Good Girl 85ML', 'Perfume', 10, 6),
  ('PRD-016', 'Hugo Boss 85ML', 'Cologne', 5, 5),
  ('PRD-017', 'Incanto Shine 85ML', 'Perfume', 0, 3),
  ('PRD-018', 'Lacoste Black 85ML', 'Cologne', 18, 6),
  ('PRD-019', 'Lacoste Red 85ML', 'Cologne', 7, 5),
  ('PRD-020', 'Meow Katy Perry 85ML', 'Perfume', 3, 3),
  ('PRD-021', 'Montblanc 85ML', 'Cologne', 22, 7),
  ('PRD-022', 'Polo Blue 85ML', 'Cologne', 9, 6),
  ('PRD-023', 'Polo Sport 85ML', 'Body Spray', 4, 5),
  ('PRD-024', 'Ralph Lauren 85ML', 'Perfume', 14, 6),
  ('PRD-025', 'Sauvage Dior 85ML', 'Cologne', 35, 10),
  ('PRD-026', 'Valaya 85ML', 'Perfume', 1, 4),
  ('PRD-027', 'Miss Dior 85ML', 'Perfume', 11, 5),
  ('PRD-028', 'Chanel No.5 85ML', 'Perfume', 6, 5),
  ('PRD-029', 'Bleu de Chanel 85ML', 'Cologne', 0, 4),
  ('PRD-030', 'Versace Eros 85ML', 'Cologne', 8, 7)
on conflict (id) do nothing;
